### ISSUE TITLE
ModuleNotFoundError: No module named 'eval_util'

### ISSUE THREAD

**Issue by gorkemozkaya** [google/youtube-8m#116]
Following the steps in README for running locally, I'm running into an error:

```
$ ls
youtube-8m
$ gcloud ai-platform local train \
> --package-path=youtube-8m --module-name=youtube-8m.train -- \
> --train_data_pattern='gs://youtube8m-ml/2/frame/train/train*.tfrecord' \
> --train_dir=/tmp/yt8m_train --frame_features --model=FrameLevelLogisticModel \
> --feature_names='rgb,audio' --feature_sizes='1024,128' --start_new_model
Traceback (most recent call last):
  File "/Users/gorkem/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/gorkem/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/gorkem/kaggle/yt8m/code/youtube-8m/train.py", line 20, in <module>
    import eval_util
ModuleNotFoundError: No module named 'eval_util'
```
Later, adding the directory `youtube-8m` to PYTHONPATH solves the problem for me, but that probably isn't the intended usage.

**Comment by XericZephyr** [comment]
Yeah. Actually the code is not structured in a favorable way for AI platform. 

https://cloud.google.com/ml-engine/docs/packaging-trainer#project-structure 

I guess only a major refactor/rework will fix this issue. :(

**Comment by x0nEAxe** [comment]
Same with cloud training, help please(
The replica master 0 exited with a non-zero status of 1. 
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.5/site-packages/youtube-8m/train.py", line 20, in <module>
    import eval_util
ImportError: No module named 'eval_util'
